name: connectivity_manager
description: "A package to monitor and manage network connectivity in Flutter apps."
version: 0.0.1
homepage: https://github.com/victorpadovam/connectivity_manager 

environment:
  sdk: '>=2.12.0 <4.0.0'  # Compatível com Dart 2.x até a versão mais recente
  flutter: ">=2.0.0"  # Compatível com Flutter 2.x até a versão mais recente

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^2.3.0  # Verifique qual a versão mais recente

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # Caso haja assets ou outras configurações específicas
